# Generated by Django 4.2.4 on 2023-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='text',
            field=models.TextField(unique=True, verbose_name='Text'),
        ),
    ]
